### ISSUE TITLE
Problem with some demos in src_test/certi1516e when run from a terminal

### ISSUE THREAD

**Issue by janettecardoso** [hla-certi/jcerti1516e#3]
Remark:   
1. All the demos below behave as expected when using Eclipse as indicated [here](https://github.com/hla-certi/jcerti1516e/wiki/Running-jcerti-demos-with-Eclipse#eclipseFromTerminal).

2. All the demos below behave as expected when the rtig is launched before the first federate.

When using the command line 
````ant -DtimeStep=2   -DupdateTime=1 -Dlookahead=0.5 demo-name-i````

In  src_test/certi1516e:

- StringFddName: If Receive.java is launched before Send: OK. But if Send.java is launched before Receive.java,  the rtig is launched, but a exception is raised in Receiver (Error [RTIinternalError](https://github.com/hla-certi/jcerti1516e/wiki/Error-Messages)).   
`demo-name-1=UAVReceive_1516e_StringFddName` and  
`demo-name-2=UAVSend_1516e_StringFddName` 

- VariableArray and FixedArray: If Receive.java is launched before Send.java, the rtig is launched, but a exception is raised in Send.java (Error [RTIinternalError](https://github.com/hla-certi/jcerti1516e/wiki/Error-Messages)). Notice that Send cannot be launched before Receive, because it does not use executeRTIG(). Otherwise the Error ["Connection to RTIA failed"](https://github.com/hla-certi/jcerti1516e/wiki/Error-Messages) appears.  
`demo-name-1=UAVReceive_1516e_FixedArray` and  
`demo-name-2=UAVSend_1516e_FixedArray`

- FixedRecord : Whatever the order of launching, the Error [NameNotFound](https://github.com/hla-certi/jcerti1516e/wiki/Error-Messages) appears.  
`demo-name-1=UAVReceive_1516e_FixedRecord` and  
`demo-name-2=UAVSend_1516e_FixedRecord`.

**Comment by janettecardoso** [comment]
FixedRecord: Solved. The FDD file had the same name that the one for demo FixedArray, but the the contents was not the same. TBD: commit this change to the repo.

**Comment by jb-ch** [comment]
Here are my investigations results, the code is ready for pushing but I don't have the right. Please give me the right.

StringFddName Issue:
- fixed in commit
- due to usage of modular fom in the joinFederation service call in /StringFddName/UavReceive.java
- correct other inconsistencies in the code such a too short BLOCKING_TIME, inconsistent loop iterations between send/receive side

FixedArray Issue:
- due to missing RTIExecutor instance which was failing RTIA launch because no RTIG was running.
- also wrong usage of modular fom in the joinFederation service call in /StringFddName/UavReceive.java
- Missing loop iterator on the sender side
- correct other inconsistencies in the code such a too short BLOCKING_TIME

VariableArray Issue:
- Again due to missing RTIExecutor instance which was failing RTIA launch because no RTIG was running.
- also wrong usage of modular fom in the joinFederation service call in /StringFddName/UavReceive.java
- Missing loop iterator on the sender side
- correct other inconsistencies in the code such a too short BLOCKING_TIME
